language: objective-c 
osx_image: xcode11.2
script: set -o pipefail && xcodebuild test -workspace material-carthage-ios.xcworkspace -scheme material-carthage-ios -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.2' | xcpretty
