language: objective-c 
osx_image: xcode12.1
script: set -o pipefail && xcodebuild test -workspace material-carthage-ios.xcworkspace -scheme material-carthage-ios -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.1' | xcpretty
